adding support for send notification operation for bgp peers
openconfig/ondatra pull request #17
Opened 2022-06-01 15:05 UTC by vhowdhur

This pull request is regarding the issue #14 
The changes include:
1. exposing the name property in the ate.proto for bgp peer
2. bgp.go file will have function to get and set name of bgp peer
3. changes in ixate.go to maintain a map of name and bgp peers 
4. implementation of the send notification operation.

Example Test-Case
```go
top := ate.Topology().New()
port := ate.Port(t, "por1")
in := top.AddInterface("ateSrc").WithPort(port)
in.IPv6().WithAddress("2000:0:0:1::b/64").WithDefaultGateway("2000:0:0:1::1")
bgp := i3.BGP().AddPeer().WithName("bgpv61")
bgp.WithPeerAddress("2000:0:0:1::1").WithTypeInternal().WithLocalASN(22)
top.Push(t).StartProtocols(t)
// for sending cease error code
top.SendBgpPeerNotification(t, 6, 1, bgp)
```

2022-06-06 21:28 UTC, greg-dennis commented
This looks fine. I'd just like to make the API more fluent. I think we need a new top-level API on ATE for "Actions," similar to "Traffic" and "Topology". Could you make it so that tests look something like:

```
ate.Actions().NewBGPPeerNotification().
    WithNotificationCode(code).
    WithNotificationSubcode(subcode).
    WithBGPPeers(peer1, peer2).
    Send(t)
  ```

2022-06-07 12:56 UTC, vhowdhur commented
Hi @greg-dennis ,
As suggested in the comments added a new actions.go file and shifted the send BGP notification operation to that.

2022-06-08 23:13 UTC, greg-dennis requested changes

2022-06-08 23:13 UTC, greg-dennis commented on actions.go
> +func (action *Actions) String() string {
In go style, receiver names should normally be 1 or 2 letters in length. Please rename "action" to "a"

2022-06-08 23:13 UTC, greg-dennis commented on actions.go
> +func (notification *BGPPeerNotification) String() string {
similarly to my comments above, please rename the receiver to "n" and change the body to:
return fmt.Sprintf("BGPPeerNotification%+v", *n)

2022-06-08 23:13 UTC, greg-dennis commented on actions.go
> +	notificationCode    int
"notification" in the field names is a bit redundant, and go style doesn't like redundancy. Please rename these fields to "code" and "subCode"

2022-06-08 23:13 UTC, greg-dennis commented on actions.go
> +	bgpPeerNames        []string
this one can just be "peerNames"

2022-06-08 23:13 UTC, greg-dennis commented on actions.go
> +// WithNotificationCode Sets the notification code that needs to be sent from BGP peer
"sets" should have lower-case "s" and comment should end with a period

2022-06-08 23:13 UTC, greg-dennis commented on actions.go
> +func (notification *BGPPeerNotification) WithNotificationCode(code int) *BGPPeerNotification {
similarly, let's rename these methods WithCode and WithSubCode

2022-06-08 23:13 UTC, greg-dennis commented on bgp.go
> +//FetchName gets the name of the peer
space after //

2022-06-08 23:13 UTC, greg-dennis commented on bgp.go
> +func (b *BGPPeer) FetchName() string {
method name should just be "Name()"

2022-06-08 23:13 UTC, greg-dennis commented on actions.go
> +	if len(notification.bgpPeerNames) == 0 {
change ate.SendBGPPeerNotification to fail if the peer names is empty, and then drop the separate check in this method for that condition.

2022-06-09 16:50 UTC, greg-dennis requested changes

2022-06-09 16:50 UTC, greg-dennis commented on actions.go
> +	// setting the default values for the respective parameters
drop this line

2022-06-09 16:50 UTC, greg-dennis commented on actions.go
> +		peerNames: []string{},
drop line to let it default to nil. Go style is to use nil for the empty slice in most cases

2022-06-09 16:50 UTC, greg-dennis commented on actions.go
> +// WithCode sets the notification code that needs to be sent from BGP peer.
drop "that needs"

2022-06-09 16:50 UTC, greg-dennis commented on actions.go
> +func (n *BGPPeerNotification) WithBGPPeers(bgpPeers ...*BGPPeer) *BGPPeerNotification {
Eliminating some more redundancy, let's call the method "WithPeers" and the parameter name "peers"

2022-06-09 16:50 UTC, greg-dennis commented on actions.go
> +func (n *BGPPeerNotification) ClearBGPPeers() *BGPPeerNotification {
I don't think this function is necessary. Someone can always create a new notification or call WithPeers with no arguments

2022-06-09 16:50 UTC, greg-dennis commented on ate.go
> +// Actions returns a handle to the various Action APIs
drop "various"

2022-06-09 16:50 UTC, greg-dennis commented on bgp.go
> +func (b *BGPPeer) Name() string {
I actually don't think this method is necessary, because the code that accesses it can just reach into the protobuf field itself

2022-06-09 16:50 UTC, greg-dennis commented on internal/ate/ixate.go
> +		return fmt.Errorf("could not update IDs for bgp peer %w", err)
per Go style, add a colon to the end of the last word preceding "%w" in all of these returned errors, e.g. "bgp peer: %w" here

2022-06-09 16:50 UTC, greg-dennis commented on internal/ate/ixate.go
> +		var breakTcpSessionOp string
shorter variables names in Go, just "op"

2022-06-09 16:50 UTC, greg-dennis commented on internal/ate/ixate.go
> +		breakTcpSessionArgs := ixweb.OpArgs{
just "args"

2022-06-10 18:14 UTC, SubhajitPalKeysight commented
@greg-dennis , would you please let us know if there is any pending item on this PR.

2022-06-10 18:17 UTC, greg-dennis commented
There is no pending item. I am putting it through our internal code review and submission process and will be exporting it back out some time next week.

2022-06-14 00:14 UTC, greg-dennis commented
The internal review is complete and has been pushed to the repo.

2022-06-14 00:14 UTC, closed without merging